// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn_reload': string;
  'error_wrapper': string;
  'fallback_ui_root': string;
  'heading': string;
  'pre': string;
}
export const cssExports: CssExports;
export default cssExports;
